name: YT Playlist Sync

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分おき
  workflow_dispatch:

# 同時実行の衝突を避ける（後から来たRunは前のRunをキャンセル）
concurrency:
  group: yt2pc-playlist-sync
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      API_KEY:     ${{ secrets.YT_API_KEY }}
      PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Write cookies
        run: |
          printf '%s' "${{ secrets.YT_COOKIES }}" > cookies.txt

      - run: pip install -r requirements.txt
      - run: python sync.py

      # ← これが “安全にpushする” ステップ
      - name: Commit & push (safe)
        run: |
          git config user.name  github-actions
          git config user.email actions@github.com

          # リモート(main)の最新に履歴だけ合わせ、作業ツリーの変更は保持
          git fetch origin main
          git reset --soft origin/main

          # 生成物だけをもう一度コミット
          git add podcasts/*.mp3 podcasts/feed.xml
          git commit -m "update feed & mp3" || exit 0

          # 確実に main へ push
          git push origin HEAD:main
