name: YT Playlist Sync
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      API_KEY:     ${{ secrets.YT_API_KEY }}
      PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - run: pip install -r requirements.txt
      - name: write cookies
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt
      - run: python sync.py
      - run: |
          git config user.name  github-actions
          git config user.email actions@github.com
          git add podcasts/feed.xml
          git commit -m "update feed" || exit 0
          git push
